### PR TITLE
added geocoder.resetInput() to "methods" in README

### PR DESCRIPTION
**Pull request by Abbe98**
No other of the mentioned method actually resets the input.

### CODE REVIEW

**Comment by louh** [comment]
Hi @Abbe98. Thanks for the PR! We didn't document certain methods because they were not designed with public use in mind (they can still change internally, for example). One of the side effects of `resetInput` I'm worried about is that it also puts focus on the input box, since it was designed to be called when a user clicks the reset (X) button in preparation for typing a new search. If you use `resetInput()` programmatically to reset the state of the geocoder, you might not be expecting that to happen.

Can you tell me more about your particular need to reset? Do you need to clear only the input element, or do you also need to reset other aspects of the geocoder (like the results list, for example)?

Thinking ahead, I think a better way to support a generic reset is to provide a new `reset()` method that is designed to be called programmatically and will actually fully reset the geocoder to a brand new state (while retaining current options). What do you think?

**Comment by Abbe98** [comment]
I'm using it to clear the input, and the result list when a user has
selected a location so that the next time the geocoder is used the user can
start typing a new location without distraction(I'm also using it to
actually close the geocoder).

```
geocoder.on('select', function(e) {
   map.setZoom(13);
   geocoder.resetInput();
});
```

A new `reset()` method would work in my case.

2016-08-07 4:57 GMT+02:00 Lou Huang notifications@github.com:

**Comment by louh** [comment]
I'm adding `reset()` in this commit: https://github.com/mapzen/leaflet-geocoder/commit/7957055a1187237498ee187a150a11a29e6a93a6

**Comment by Abbe98** [comment]
Thanks! :+1:

**Pull request closed without merging**
