### PR TITLE
fix permission, remove useless executable

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by louh** [comment]
@PeterDaveHello, is this superceded by https://github.com/mapzen/leaflet-geocoder/pull/88?

If not, can you explain what you mean by fixing permissions and removing an executable?

**Comment by PeterDaveHello** [comment]
They actually don't need executable permission.

**Comment by louh** [comment]
Got it. Good point, thank you.

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request merged**
