### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### pelias/leaflet-geocoder now has a Chat Room on Gitter

@riordan has just created a chat room. You can visit it here: [https://gitter.im/pelias/leaflet-geocoder](https://gitter.im/pelias/leaflet-geocoder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/pelias/leaflet-geocoder?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by louh** [comment]
Is it normal for every repository to have its own gitter room? as opposed to having all the related projects share the "main" Pelias gitter channel?

**Comment by missinglink** [comment]
I think it would be better to only have maybe one room for 'mapzen' and then one room for the project 'pelias' otherwise there are going to end up being a bunch of empty rooms instead of one active room with a quick feedback loop?

:+1: for closing this, cc/ @riordan 

https://song-of-github.herokuapp.com/?username=gitter-badger

**Comment by riordan** [comment]
Excellent.

On Wed, Oct 7, 2015 at 5:47 AM, Peter Johnson a.k.a. insertcoffee <
notifications@github.com> wrote:

> I think it would be better to only have maybe one room for 'mapzen' and
> then one room for the project 'pelias' otherwise there are going to end up
> being a bunch of empty rooms instead of one active room with a quick
> feedback loop?
> 
> [image: :+1:] for closing this, cc/ @riordan https://github.com/riordan
> 
> https://song-of-github.herokuapp.com/?username=gitter-badger
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pelias/leaflet-geocoder/pull/57#issuecomment-146134847
> .

## 

David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan https://twitter.com/riordan | gpg 235D9DC95EF6277C
https://keybase.io/riordan
Mapzen | https://mapzen.com | @mapzen https://twitter.com/search

**Comment by louh** [comment]
I could update this with the canonical pelias project chatroom.  https://gitter.im/pelias/ ? or  https://gitter.im/pelias/api ?

**Comment by missinglink** [comment]
I'll leave this up to whoever is going to be hanging out in there and handling the support requests. I'd prefer to be pinged-in if someone needs more specific help, I assume the same goes for you @louh?

**Comment by louh** [comment]
Yep -- that works for me.

**Pull request closed without merging**
